FROM alpine:latest
WORKDIR /app
RUN mkdir -p /app/data && chmod 777 /app/data
COPY server.lua ./
COPY vibescript.out ./
RUN  chmod +x ./vibescript.out
CMD ["./vibescript.out", "server.lua", "--start", "3000", "--end", "3100"]
