services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "3000-3200:3000-3200"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  api1: &api
    image: luizcordista/rinha-backend-2025:latest
    hostname: api1
    environment:
      - APP_PORT=8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
      - WORKER_CONCURRENCY=16
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "30MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - APP_PORT=8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2
      - WORKER_CONCURRENCY=16

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true