version: '3.8'
services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "3000-3200:3000-3200"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  api1:
    build:
      context: .
      dockerfile: Dockerfile.server1
    container_name: api1
    volumes:
      - .:/app
    working_dir: /app
    command: vibescript server.lua --start 3000 --end 3100
    ports:
      - "3000-3100:3000-3100"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "30MB"

  api2:
    build:
      context: .
      dockerfile: Dockerfile.server2
    container_name: api2
    volumes:
      - .:/app
    working_dir: /app
    command: vibescript server.lua --start 3101 --end 3200
    ports:
      - "3101-3200:3101-3200"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "30MB"

  health_checker:
    build:
      context: .
      dockerfile: Dockerfile.health_checker
    container_name: health_checker
    volumes:
      - .:/app
    working_dir: /app
    command: vibescript health_checker.lua

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true